# Service to expose web frontend
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: metrics
spec:
  selector:
    group: api
  ports:
  - name: metrics
    protocol: TCP
    port: 9102
    targetPort: 9102

---
# API service version 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        group: api
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/service-tags": "v0.0.2"
    spec:
      containers:
      - name: api
        image: nicholasjackson/translate-api:0.0.2
        ports:
        - containerPort: 3000
        env:
        - name: GOOGLE_PROJECT
          value: consul-canary
        - name: GOOGLE_REDISHOST
          valueFrom:
            secretKeyRef:
              name: redis-host
              key: hostname
        - name: GOOGLE_REDISPORT
          valueFrom:
            secretKeyRef:
              name: redis-host
              key: port
        - name: ORIGIN
          value: http://web.translate.demo.gs
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secret/credentials.json
        volumeMounts:
        - name: gcloud
          mountPath: "/etc/secret"
          readOnly: true
      volumes:
        - name: gcloud
          secret:
            secretName: google-application-credentials
