---
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress
spec:
  listeners:
    - port: 80
      protocol: http
      services:
        - name: api
        - hosts: ['api.translate.demo.gs']
